mpiexec -n 8 python main_asyn.py 1 
mpiexec -n 8 python main_asyn.py 2
mpiexec -n 8 python main_asyn.py 3
mpiexec -n 8 python main_asyn.py 4
mpiexec -n 8 python main_asyn.py 5
mpiexec -n 8 python main_asyn.py 6
mpiexec -n 8 python main_asyn.py 7
mpiexec -n 8 python main_asyn.py 8
mpiexec -n 8 python main_asyn.py 9
mpiexec -n 8 python main_asyn.py 10
mpiexec -n 8 python main_asyn.py 11 
mpiexec -n 8 python main_asyn.py 12
mpiexec -n 8 python main_asyn.py 13
mpiexec -n 8 python main_asyn.py 14
mpiexec -n 8 python main_asyn.py 15
mpiexec -n 8 python main_asyn.py 16
mpiexec -n 8 python main_asyn.py 17
mpiexec -n 8 python main_asyn.py 18
mpiexec -n 8 python main_asyn.py 19
mpiexec -n 8 python main_asyn.py 20
mpiexec -n 8 python main_asyn.py 21 
mpiexec -n 8 python main_asyn.py 22
mpiexec -n 8 python main_asyn.py 23
mpiexec -n 8 python main_asyn.py 24
mpiexec -n 8 python main_asyn.py 25
mpiexec -n 8 python main_asyn.py 26
mpiexec -n 8 python main_asyn.py 27
mpiexec -n 8 python main_asyn.py 28
mpiexec -n 8 python main_asyn.py 29
mpiexec -n 8 python main_asyn.py 30
mpiexec -n 8 python main_asyn.py 31 
mpiexec -n 8 python main_asyn.py 32
mpiexec -n 8 python main_asyn.py 33
mpiexec -n 8 python main_asyn.py 34
mpiexec -n 8 python main_asyn.py 35
mpiexec -n 8 python main_asyn.py 36
mpiexec -n 8 python main_asyn.py 37
mpiexec -n 8 python main_asyn.py 38
mpiexec -n 8 python main_asyn.py 39
mpiexec -n 8 python main_asyn.py 40
mpiexec -n 8 python main_asyn.py 41 
mpiexec -n 8 python main_asyn.py 42
mpiexec -n 8 python main_asyn.py 43
mpiexec -n 8 python main_asyn.py 44
mpiexec -n 8 python main_asyn.py 45
mpiexec -n 8 python main_asyn.py 46
mpiexec -n 8 python main_asyn.py 47
mpiexec -n 8 python main_asyn.py 48
mpiexec -n 8 python main_asyn.py 49
mpiexec -n 8 python main_asyn.py 50
mpiexec -n 8 python main_asyn.py 51 
mpiexec -n 8 python main_asyn.py 52
mpiexec -n 8 python main_asyn.py 53
mpiexec -n 8 python main_asyn.py 54
mpiexec -n 8 python main_asyn.py 55
mpiexec -n 8 python main_asyn.py 56
mpiexec -n 8 python main_asyn.py 57
mpiexec -n 8 python main_asyn.py 58
mpiexec -n 8 python main_asyn.py 59
mpiexec -n 8 python main_asyn.py 60
mpiexec -n 8 python main_asyn.py 61 
mpiexec -n 8 python main_asyn.py 62
mpiexec -n 8 python main_asyn.py 63
mpiexec -n 8 python main_asyn.py 64
mpiexec -n 8 python main_asyn.py 65
mpiexec -n 8 python main_asyn.py 66
mpiexec -n 8 python main_asyn.py 67
mpiexec -n 8 python main_asyn.py 68
mpiexec -n 8 python main_asyn.py 69
mpiexec -n 8 python main_asyn.py 70
mpiexec -n 8 python main_asyn.py 71 
mpiexec -n 8 python main_asyn.py 72
mpiexec -n 8 python main_asyn.py 73
mpiexec -n 8 python main_asyn.py 74
mpiexec -n 8 python main_asyn.py 75
mpiexec -n 8 python main_asyn.py 76
mpiexec -n 8 python main_asyn.py 77
mpiexec -n 8 python main_asyn.py 78
mpiexec -n 8 python main_asyn.py 79
mpiexec -n 8 python main_asyn.py 80
mpiexec -n 8 python main_asyn.py 81 
mpiexec -n 8 python main_asyn.py 82
mpiexec -n 8 python main_asyn.py 83
mpiexec -n 8 python main_asyn.py 84
mpiexec -n 8 python main_asyn.py 85
mpiexec -n 8 python main_asyn.py 86
mpiexec -n 8 python main_asyn.py 87
mpiexec -n 8 python main_asyn.py 88
mpiexec -n 8 python main_asyn.py 89
mpiexec -n 8 python main_asyn.py 90
mpiexec -n 8 python main_asyn.py 91 
mpiexec -n 8 python main_asyn.py 92
mpiexec -n 8 python main_asyn.py 93
mpiexec -n 8 python main_asyn.py 94
mpiexec -n 8 python main_asyn.py 95
mpiexec -n 8 python main_asyn.py 96
mpiexec -n 8 python main_asyn.py 97
mpiexec -n 8 python main_asyn.py 98
mpiexec -n 8 python main_asyn.py 99
mpiexec -n 8 python main_asyn.py 100