mpiexec -n 8 python main.py 68
mpiexec -n 8 python main.py 69
mpiexec -n 8 python main.py 70
mpiexec -n 8 python main.py 71 
mpiexec -n 8 python main.py 72
mpiexec -n 8 python main.py 73
mpiexec -n 8 python main.py 74
mpiexec -n 8 python main.py 75
mpiexec -n 8 python main.py 76
mpiexec -n 8 python main.py 77
mpiexec -n 8 python main.py 78
mpiexec -n 8 python main.py 79
mpiexec -n 8 python main.py 80
mpiexec -n 8 python main.py 81 
mpiexec -n 8 python main.py 82
mpiexec -n 8 python main.py 83
mpiexec -n 8 python main.py 84
mpiexec -n 8 python main.py 85
mpiexec -n 8 python main.py 86
mpiexec -n 8 python main.py 87
mpiexec -n 8 python main.py 88
mpiexec -n 8 python main.py 89
mpiexec -n 8 python main.py 90
mpiexec -n 8 python main.py 91 
mpiexec -n 8 python main.py 92
mpiexec -n 8 python main.py 93
mpiexec -n 8 python main.py 94
mpiexec -n 8 python main.py 95
mpiexec -n 8 python main.py 96
mpiexec -n 8 python main.py 97
mpiexec -n 8 python main.py 98
mpiexec -n 8 python main.py 99
mpiexec -n 8 python main.py 100